### PR TITLE
Added Sorting Methods

### PR DESCRIPTION
**Pull request by Vishesh-dd4723**
# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [ ] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [ ] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [ ] pytest
- [ ] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``
- ``python`` = ``python3 -V (unix) / py -3 -V (Windows-Python launcher)``

linked issue #NOMOR_ISSUE

### CODE REVIEW

**Comment by Vishesh-dd4723** [comment]
Respected reviewer, my #48 and #49 didn't pass the tests so my latest PR(#50) should be considered, not #48 as #48 has flaws that I resolved in #50. So please accept #50, not #48 nor #49.

**Comment by norinorin** [comment]
Hai, bisa dibaca kembali CONTRIBUTING.md-nya. Maaf kita close dulu, bisa re-open kalau commit message-nya udah sesuai dengan spesifikasi. Terima kasih!

**Comment by norinorin** [comment]
> Respected maintainers, my #48 and #49 didn't pass the tests so my latest PR(#50) should be considered, not #48 as #48 has flaws that I resolved in #50. So please accept #50, not #48 nor #49.

Oh, sure! Are you by any chance, not an Indonesian?

**Comment by Vishesh-dd4723** [comment]
No, I am Indian. But I used a translator to help this repo.

**Comment by norinorin** [comment]
Okay, that's cool. Thanks for trying to contribute. Can you understand the CONTRIBUTING.md? Want me to translate it for ya or something before we get into the reviews?

**Comment by Vishesh-dd4723** [comment]
I got them. It suggests using flake8 and pytest to pass online judges. Then only, my PR will be considered.

**Comment by norinorin** [comment]
Just to add up, it also mentions the use of conventional commit messages which can be read [here](https://www.conventionalcommits.org/en/v1.0.0/)

**Pull request closed without merging**
