### PR TITLE
feat: bubble_sort.py

### PR DESCRIPTION
**Pull request by Vishesh-dd4723**
# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [ ] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/PythonAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan docstring yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

##### Unit Testing dan Linting:
- [x] pytest
- [x] flake8

# Environment
Saya menggunakan (I'm using):

- ``os`` = ``linux / windows / macOS``
- ``python`` = ``python3 -V (unix) / py -3 -V (Windows-Python launcher)``

linked issue #NOMOR_ISSUE

### CODE REVIEW

**Comment by norinorin** [comment]
Duplicate of #48

**Comment by Vishesh-dd4723** [comment]
Respected reviewer, my #48 and #49 didn't pass the tests so my latest PR(#50) should be considered, not #48 as #48 has flaws that I resolved in #50. So please accept #50, not #48 nor #49.

**Comment by norinorin** [comment]
As I mentioned earlier in #48, can you rebase so that the commit messages comply with the conventional commits?

**Comment by Vishesh-dd4723** [comment]
Please give me some time to get familiar with conventional commits as I never heard of them before. Thanks

**Comment by norinorin** [comment]
All good, take your time.

**Comment by Vishesh-dd4723** [comment]
Now, I followed the conventional commits. You can go ahead.

**Comment by norinorin** [comment]
It's not really necessary for the PR title, rather the commit messages. So I'd suggest you do an interactive rebase.

**Comment by Vishesh-dd4723** [comment]
I tried rebasing. Hope it worked.

**Comment by norinorin** [comment]
> I tried rebasing. Hope it worked.

The commit messages haven't changed yet.

**Comment by norinorin** [comment]
Sorry, we're just told that we're not supposed to accept foreign PRs unless you speak Indonesian (instead of using a translator). This repo is currently targeted towards local developers, thus it has to be in Indonesian. We do appreciate your PR, but we'll have to close this.

**Comment by norinorin** [comment]
> Can you give it the ''hacktoberfest-accepted' label if you can't merge it but find it relevant though because it is showing spam at the Hactoberfest portal and there is a chance that they can flag my GitHub account also for spamming. Thanks :)

Unfortunately, no. The label should only be given to valid PRs which isn't the case here. We do appreciate your effort in trying to contribute, but this org is specifically targeted towards Indonesian people as I've mentioned before. So, unless you speak Indonesian and make a valid PR, we can't add the label. Sorry.

**Pull request closed without merging**
